---
- name: Create S3 bucket
  hosts: localhost
  gather_facts: no

  vars:
    bucket_name: aish-930-ans-project
    aws_region: us-east-1

  tasks:
    - name: Create S3 bucket
      amazon.aws.s3_bucket:
        name: "{{ bucket_name }}"
        state: present
        region: "{{ aws_region }}"
